//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafffe_Sytem.A.M.A
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Coffee_SystemEntities : DbContext
    {
        public Coffee_SystemEntities()
            : base("name=Coffee_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill_has_Products> Bill_has_Products { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<Posistion> Posistions { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Sys_Info> Sys_Info { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
