//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafffe_Sytem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int C_ID { get; set; }
        public string C_Name { get; set; }
        public long C_Phone_Number { get; set; }
        public string C_Address { get; set; }
    }
}
